### ISSUE TITLE
Will this project support SpecInfer?

### ISSUE THREAD

**Issue by Repeater9** [hemingkx/Spec-Bench#16]
Thank you for your awesome work!

**Comment by hemingkx** [comment]
I'm glad you're interested in our Spec-Bench platform! As mentioned in the paper, we've integrated open-source, ready-to-use Spec implementations, following the [Medusa](https://github.com/FasterDecoding/Medusa) and [FastChat](https://github.com/lm-sys/FastChat/blob/main/fastchat/llm_judge/gen_model_answer.py) evaluation format. However, we welcome integrations with other models via pull requests if you are interested. 😊
