### ISSUE TITLE
Does this code support batch sizes greater than 1 in the SPS method?

### ISSUE THREAD

**Issue by deafTim** [hemingkx/Spec-Bench#17]
I encountered the following error:
```
ValueError: assisted generate is only supported for batch_size = 1
```

**Comment by hemingkx** [comment]
Apologies for the delayed response! We use the HuggingFace implementation of [SpS](https://github.com/huggingface/transformers/blob/v4.37.1/src/transformers/generation/utils.py) with transformers 4.37.1, which only supports SpS for batch_size = 1. You can update to the latest Hugging Face version if it supports batched SpS, or modify the code yourself.
