### ISSUE TITLE
You are using a model of type qwen2 to instantiate a model of type llama. This is not supported for all configurations of models and can yield errors.

### ISSUE THREAD

**Issue by HaoWuSR** [hemingkx/Spec-Bench#18]
Thank you so much for your awesome work!
When I evaluate the Qwen2-7B-Instruct by using EGALE2，it leads to following issues ：
`You are using a model of type qwen2 to instantiate a model of type llama. This is not supported for all configurations of models and can yield errors.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:10<00:00,  2.58s/it]
Some weights of LlamaForCausalLM were not initialized from the model checkpoint at /workspace/suri/model/Qwen2-7B-Instruct and are newly initialized: ['model.layers.0.self_attn.rotary_emb.inv_freq', 'model.layers.1.self_attn.rotary_emb.inv_freq', 'model.layers.10.self_attn.rotary_emb.inv_freq', 'model.layers.11.self_attn.rotary_emb.inv_freq', 'model.layers.12.self_attn.rotary_emb.inv_freq', 'model.layers.13.self_attn.rotary_emb.inv_freq', 'model.layers.14.self_attn.rotary_emb.inv_freq', 'model.layers.15.self_attn.rotary_emb.inv_freq', 'model.layers.16.self_attn.rotary_emb.inv_freq', 'model.layers.17.self_attn.rotary_emb.inv_freq', 'model.layers.18.self_attn.rotary_emb.inv_freq', 'model.layers.19.self_attn.rotary_emb.inv_freq', 'model.layers.2.self_attn.rotary_emb.inv_freq', 'model.layers.20.self_attn.rotary_emb.inv_freq', 'model.layers.21.self_attn.rotary_emb.inv_freq', 'model.layers.22.self_attn.rotary_emb.inv_freq', 'model.layers.23.self_attn.rotary_emb.inv_freq', 'model.layers.24.self_attn.rotary_emb.inv_freq', 'model.layers.25.self_attn.rotary_emb.inv_freq', 'model.layers.26.self_attn.rotary_emb.inv_freq', 'model.layers.27.self_attn.rotary_emb.inv_freq', 'model.layers.3.self_attn.rotary_emb.inv_freq', 'model.layers.4.self_attn.rotary_emb.inv_freq', 'model.layers.5.self_attn.rotary_emb.inv_freq', 'model.layers.6.self_attn.rotary_emb.inv_freq', 'model.layers.7.self_attn.rotary_emb.inv_freq', 'model.layers.8.self_attn.rotary_emb.inv_freq', 'model.layers.9.self_attn.rotary_emb.inv_freq']`

Have u meet this problem？ 
Regards

**Comment by hemingkx** [comment]
I'm glad you found our work helpful! 😊

We only compare and integrate each method into Spec-Bench using Vicuna-v1.3. If you'd like to try different LLMs, you can modify the code following the [original repository](https://github.com/SafeAILab/EAGLE/tree/main).

We made the smallest modifications to integrate each method into Spec-Bench. Feel free to adjust the code on your own. If you need any help, please feel free to discuss with us.

Best regards.

**Comment by FWXT** [comment]
hi @HaoWuSR , do you have any speed up in qwen2 series? I test qwen2.5-coder-7b in a100 with [yuhuili/EAGLE-Qwen2-7B-Instruct](https://huggingface.co/yuhuili/EAGLE-Qwen2-7B-Instruct) as spec-model. But no speed up. However I found speed up in vicuna series. Is it due to the quality of spec-model?
