### ISSUE TITLE
REST methodology verification process

### ISSUE THREAD

**Issue by jivanph** [hemingkx/Spec-Bench#3]
I noticed that in Table 3 you present a summary of different decoding methodologies.

In particular, you present REST as a methodology amenable to Nucleus sampling, but on reading the REST methodology paper, it's not clear how they establish that their methodology maintains the same output distribution from a LLM.

**Comment by hemingkx** [comment]
Hi,

We checked Section 4.1 (Experimental Setup) in the [REST](http://arxiv.org/abs/2311.08252) paper, which claims that their results are identical to those generated by autoregressive generation. Moreover, the authors of REST have provided a detailed code implementation in response to a similar query, which you can find [here](https://github.com/FasterDecoding/REST/issues/5#issuecomment-1965648290). 

We hope this addresses your concern. Please feel free to reach out if you have any more questions or require further clarification.

**Comment by jivanph** [comment]
Thank you so much for your response. It clarify my understanding of their methodology.
